development:
  cloud_name: thiagovernetti
  api_key: '388373179438396'
  api_secret: hXdI767fMhUh4hk-Cw2EmMFv9Ts
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: thiagovernetti
  api_key: '388373179438396'
  api_secret: hXdI767fMhUh4hk-Cw2EmMFv9Ts
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: thiagovernetti
  api_key: '388373179438396'
  api_secret: hXdI767fMhUh4hk-Cw2EmMFv9Ts
  enhance_image_tag: true
  static_file_support: false