meta_product_name: "Bora!"
meta_title: "Bora! - Encontre companhia para sua próxima aventura"
meta_description: "O Bora é uma plataforma que conecta viajantes do mundo inteiro."
meta_image: "logo2.png" # should exist in `app/assets/images/`